linuxserver/docker-letsencrypt

root/etc/cont-init.d/50-config
root/etc/fail2ban/fail2ban.local
root/etc/services.d/fail2ban/run

1) fix fail2ban start up
2) fix fail2ban config and log location
3) correct permissions

various bug fixes

---

READMETEMPLATE.md

test PR with ignores in place

---

root/etc/cont-init.d/50-config

prevent nesting dolls of symlinks

---

root/etc/logrotate.d/lerotate

no date extension for letsencrypt logrotate

---

root/etc/services.d/cron/run

remove cron service because baseimage has it

---

Dockerfile

switch to the nginx alpine testbed baseimage

---

root/etc/cont-init.d/50-config

create log files if necessary so fail2ban doesn't fail

---

root/etc/cont-init.d/50-config

fix deletion of symlink after failed install

---

Dockerfile
root/defaults/default

switch base to alpine.nginx

---

root/etc/cont-init.d/50-config

add support for user crontabs

---

root/etc/cont-init.d/50-config

update log permissions

---

root/etc/cont-init.d/50-config

Add support for custom fail2ban actions

---

root/etc/cont-init.d/50-config

+ knocking off a few linting warnings from the init script

try to reduce some of the shellchecks

---

root/etc/cont-init.d/50-config

Changes for linting recommendations

---

root/etc/cont-init.d/50-config

+ add limited no of shellcheck disables to give good baseline of zero for introduced lint warnings down the line

Shellcheck Disables for baseline zero

---

Dockerfile
READMETEMPLATE.md
root/etc/cont-init.d/50-config

update readme, add s6 exit

---

root/defaults/default
root/defaults/proxy.conf
root/etc/cont-init.d/50-config

reverse proxy support and samples + relative path cert symlinks

---

root/defaults/default

fix typo in site config

---

Dockerfile
README.md

Add curl package

---

Dockerfile
README.md

Add gd and mcrypt

---

Dockerfile

Add php-mysql support

---

Dockerfile
README.md

Add php5-ctype and php5-openssl

---

Dockerfile
README.md
root/defaults/default

alpine 3.5 and php7

---

Dockerfile

+ vanity and sanity sort on dependencies
+ remove dependencies present in baseimage

resort dependendcies alphabetically, remove some in baseimage

---

Dockerfile
README.md

Add php7-xml

---

Dockerfile
README.md

Add php7-dom, php7-iconv and php7-pdo_sqlite

---

Dockerfile
README.md
root/etc/cont-init.d/50-config

Update fail2ban defaults in /config

---

README.md
root/etc/cont-init.d/50-config
root/etc/logrotate.d/fail2ban
root/etc/logrotate.d/lerotate

Fix log permissions

---

Dockerfile
README.md

Add php7-bz2 for bzip2

---

README.md
root/etc/cont-init.d/50-config

Make e-mail optional, update deprecated certbot option and update readme

---

README.md
root/etc/cont-init.d/50-config

Add support for extra domains

---

Dockerfile
root/etc/cont-init.d/50-config

fix copying of fail2ban defaults

---

Dockerfile

php7-tokenizer

---

Dockerfile
README.md
root/etc/services.d/memcached/run

Add memcached service

---

README.md
root/etc/cont-init.d/50-config
root/etc/services.d/fail2ban/run

Manage fail2ban via s6

---

README.md
root/etc/cont-init.d/50-config

Add support for http validation on port 80

---

README.md
root/etc/cont-init.d/50-config

Halt the container if validation fails, instead of a stop

---

Dockerfile
README.md

adds php7-pgsql

---

root/defaults/proxy-confs/lidarr.subdomain.conf.sample
root/defaults/proxy-confs/lidarr.subfolder.conf.sample

Pretty much `s/radarr/lidarr` and `s/7878/8686`
I only tested the subdomain conf, works like a charm

add lidarr proxy confs, pretty much same as radarr

---

root/defaults/proxy-confs/plex.subfolder.conf.sample

Add proxy sample for plex subfolder

---

root/defaults/proxy-confs/couchpotato.subfolder.conf.sample

Add couchpotato subfolder proxy sample

---

root/defaults/proxy-confs/bazarr.subfolder.conf.sample

Add bazarr subfolder proxy sample

---

root/defaults/proxy-confs/headphones.subfolder.conf.sample

Add headphones subfolder proxy sample

---

README.md
root/defaults/proxy-confs/headphones.subfolder.conf.sample
root/defaults/proxy-confs/jackett.subdomain.conf.sample
root/defaults/proxy-confs/jackett.subfolder.conf.sample
root/defaults/proxy-confs/plex.subfolder.conf.sample

Add jackett api locations

---

root/defaults/proxy-confs/sickrage.subfolder.conf.sample

Add sickrage subfolder proxy sample

---

root/defaults/proxy-confs/mylar.subfolder.conf.sample

Add mylar subfolder proxy sample

---

root/defaults/proxy-confs/medusa.subfolder.conf.sample

Add medusa subfolder proxy sample

---

root/defaults/proxy-confs/lazylibrarian.subfolder.conf.sample

Add lazylibrarian subfolder proxy sample

---

root/defaults/proxy-confs/headphones.subdomain.conf.sample
root/defaults/proxy-confs/lazylibrarian.subdomain.conf.sample
root/defaults/proxy-confs/medusa.subdomain.conf.sample
root/defaults/proxy-confs/mylar.subdomain.conf.sample
root/defaults/proxy-confs/sickrage.subdomain.conf.sample

I have not actually run testing on these but they should all work since their counterparts in folders all work and these are all pretty basic (no rewrites).

Subdomains

---

root/defaults/proxy-confs/nextcloud.subfolder.conf.sample

Instructions for what to add to the nextcloud config are included as a comment.
I've tested this setup myself and haven't run into any problems so far.

Add nextcloud subfolder config

---

root/defaults/proxy-confs/netdata.subdomain.conf.sample
root/defaults/proxy-confs/netdata.subfolder.conf.sample

Add netdata proxy samples

---

root/defaults/proxy-confs/deluge.subdomain.conf.sample
root/defaults/proxy-confs/deluge.subfolder.conf.sample

Finally got this one figured out.

Add deluge proxy confs

---

root/defaults/proxy-confs/bazarr.subfolder.conf.sample
root/defaults/proxy-confs/deluge.subfolder.conf.sample
root/defaults/proxy-confs/netdata.subfolder.conf.sample
root/defaults/proxy-confs/rutorrent.subfolder.conf.sample

Add redirects to proxy confs

---

root/defaults/proxy-confs/airsonic.subfolder.conf.sample

Added subfolder proxy pass for Airsonic

Added Airsonic proxy-conf

---

root/defaults/proxy-confs/flood.subdomain.conf.sample
root/defaults/proxy-confs/flood.subfolder.conf.sample

Add flood proxy conf samples

---

root/defaults/proxy-confs/netdata.subfolder.conf.sample

Update netdata subfolder proxy conf

---

root/defaults/proxy-confs/portainer.subfolder.conf.sample

Add Portainer subfolder proxy conf sample

---

root/defaults/proxy-confs/duplicati.subdomain.conf.sample
root/defaults/proxy-confs/duplicati.subfolder.conf.sample

Tested.
This has been on my list FOREVER and I finally got it working my disabling the auth built into duplicati.

Add Duplicati proxy configs

---

root/defaults/proxy-confs/phpmyadmin.subdomain.conf.sample
root/defaults/proxy-confs/phpmyadmin.subfolder.conf.sample

Add phpMyAdmin proxy configs

---

README.md
root/defaults/proxy-confs/_readme
root/defaults/proxy-confs/airsonic.subfolder.conf.sample
root/defaults/proxy-confs/deluge.subfolder.conf.sample
root/defaults/proxy-confs/duplicati.subdomain.conf.sample
root/defaults/proxy-confs/duplicati.subfolder.conf.sample
root/defaults/proxy-confs/flood.subdomain.conf.sample
root/defaults/proxy-confs/flood.subfolder.conf.sample
root/defaults/proxy-confs/netdata.subfolder.conf.sample
root/defaults/proxy-confs/ombi.subfolder.conf.sample
root/defaults/proxy-confs/phpmyadmin.subdomain.conf.sample
root/defaults/proxy-confs/phpmyadmin.subfolder.conf.sample
root/defaults/proxy-confs/pihole.subdomain.conf.sample
root/defaults/proxy-confs/pihole.subfolder.conf.sample
root/defaults/proxy-confs/plex.subdomain.conf.sample
root/defaults/proxy-confs/plex.subfolder.conf.sample
root/defaults/proxy-confs/plexwebtools.subdomain.conf.sample
root/defaults/proxy-confs/plexwebtools.subfolder.conf.sample
root/defaults/proxy-confs/portainer.subdomain.conf.sample
root/defaults/proxy-confs/portainer.subfolder.conf.sample
root/defaults/proxy-confs/pydio.subdomain.conf.sample
root/defaults/proxy-confs/rutorrent.subfolder.conf.sample
root/defaults/proxy-confs/thelounge.subdomain.conf.sample
root/defaults/proxy-confs/thelounge.subfolder.conf.sample

combined reverse proxy updates

---

root/defaults/proxy-confs/glances.subdomain.conf.sample
root/defaults/proxy-confs/glances.subfolder.conf.sample

Add proxy configs for Glances

---

README.md
root/etc/cont-init.d/50-config

remove renewal during container start

---

readme-vars.yml
root/etc/services.d/memcached/run

remove memcached due to seccomp errors

---

README.md
readme-vars.yml

Dynamic readme

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

Rebase to alpine 3.9

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

add gnupg package

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

add php intl and posix modules

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

switch packages to py3, clean up python cache, rebase aarch64 to 3.8

---

Dockerfile.aarch64
README.md
readme-vars.yml

rebase aarch64 to 3.9

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

add php-redis

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

remove default.conf when nginx is updated in downstream image

---

README.md
readme-vars.yml
root/etc/cont-init.d/15-urllib

 remove botocore/urllib patch

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

adds package nginx-mod-http-geoip2 and libmaxminddb
https://pkgs.alpinelinux.org/package/v3.10/main/x86_64/nginx-mod-http-geoip2
https://pkgs.alpinelinux.org/package/v3.10/main/x86_64/libmaxminddb
#176 

adds package nginx-mod-http-geoip2 and libmaxminddb

---

README.md
readme-vars.yml
root/etc/cont-init.d/50-config

create GeoIP2 db during container start

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

add php7-ldap, remove geoip v1

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

@aptalca Dunno if you have any reservations or not, I've tested all the builds locally.
Closes https://github.com/linuxserver/docker-letsencrypt/issues/348

Add php7-bcmath php7-pear php7-xmlrpc

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

add php7-ftp

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/dns-conf/inwx.ini
root/etc/cont-init.d/50-config

I added the dns plugin for inwx.de, a popular german DNS-provider.
The plugin can be found here.
I tested it and it worked fine in my setup.
Sorry for posting this a second time, I squashed my commits into one.
I'm not very proficient with git...

Adding certbot-dns-inwx

---

README.md
readme-vars.yml
root/etc/cont-init.d/50-config

move geoip2 db to config

---

README.md
readme-vars.yml
root/defaults/proxy.conf

update host header to fix CSRF issues

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

Add php7-pecl-imagick

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/etc/nginx/modules/http_geoip2.conf
root/etc/nginx/modules/stream_geoip2.conf

remove geoip2 patch, fixed upstream

---

README.md
readme-vars.yml
root/defaults/nginx.conf

turn off resty core to get rid of error in log

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/dns-conf/transip.ini
root/etc/cont-init.d/50-config

Added provider Transip.
Certbot using dns TXT records via Transip API.
TransIP(.nl) is know dutch a domain name registration company. With use of their API, certbot can use dns TXT records.
Setup with my own API key and generated let's encrypt certificate.

add support for Transip provider with dns validation

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

Add php7-pdo_odbc

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml

fix cryptography version mismatch

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/dns-conf/gandi.ini
root/etc/cont-init.d/50-config

Added provider Gandi.
Gandi is a domain registrar which also provides a DNS nameserver service which has (as of somewhat recently) an API. [Someone already wrote the Certbot plugin](https://github.com/obynio/certbot-plugin-gandi) to handle these challenges; this integrates it to the Docker image as an allowed DNS challenge source.
Generated and configured API key; generated SSL cert for a domain registered+nameservered through Gandi, worked great.
https://github.com/obynio/certbot-plugin-gandi
The …

feat(dns-gandi): add support for Gandi LiveDNS challenges

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/dns-conf/domeneshop.ini
root/etc/cont-init.d/50-config

add support for domeneshop dns

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/dns-conf/cpanel.ini
root/etc/cont-init.d/50-config

Add cpanel dns validation

---

README.md
readme-vars.yml
root/etc/cont-init.d/50-config

deprecate tls-sni, remove from docs

---

readme-vars.yml
root/etc/cont-init.d/50-config

change dns-confs to 700; change files to 600
permissions for the ini files which could contain api keys and/or passwords are currently world and group readable. While it may be necessary to give group read permissions, world should definitely not be there on these files.
a user on discord tested manually
[https://github.com/linuxserver/docker-letsencrypt/issues/413](https://github.com/linuxserver/docker-letsencrypt/issues/413)

modify dns-conf permissions

---

README.md
readme-vars.yml
root/etc/cont-init.d/60-renew

~~Do not merge yet.~~
~~This will need some local testing when built~~

attempt renewal on start if expired

---

root/defaults/ldap.conf

typo & notes

---

README.md
readme-vars.yml
root/defaults/authelia-location.conf
root/defaults/authelia-server.conf

Please merge https://github.com/linuxserver/reverse-proxy-confs/pull/172 first

tweak authelia confs to supersede regex

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/default
root/defaults/ldap.conf

Merge https://github.com/linuxserver/reverse-proxy-confs/pull/173 first so they get pulled in

Rebasing to Alpine 3.12, change ldap login endpoint
