README.md
root/etc/cont-init.d/50-config

This pull request will allow extra non-subdomains to be added to the the generated certificates without impacting existing installations and resolves https://github.com/linuxserver/docker-letsencrypt/issues/50 in a simple, non-complicated way.
Example Usage:
```
docker create \
-e "URL=primarydomain.com" \
-e "SUBDOMAINS=one,two" \
-e "EXTRA_DOMAINS=secondarydomain.co.uk,tertiarydomain.org" \
linuxserver/letsencrypt
```

Added EXTRA_DOMAINS option to obtain certs for non sub-domains

---

Dockerfile
README.md

This PR adds the **php-soap module** to the image, installing it through the Dockerfile.

Add php7 soap module

---

README.md
root/defaults/proxy-confs/syncthing.subdomain.conf.sample

added working syncthing subdomain proxy .conf template for linuxserver.io syncthing docker

added working syncthing subdomain proxy .conf template for linuxserver.io syncthing docker

---

root/defaults/proxy-confs/radarr.subdomain.conf.sample
root/defaults/proxy-confs/sabnzbd.subdomain.conf.sample
root/defaults/proxy-confs/sonarr.subdomain.conf.sample
root/defaults/proxy-confs/tautulli.subdomain.conf.sample

For apps with API blocks the baseurl may possibly exist if a user is using both subdomain and subfolder at the same time (I do this). Adding these little bits allows to the subdomain blocks with API locations makes them work both with and without a baseurl on subdomains.

Add optional baseurls to subdomain proxy confs

---

root/defaults/proxy-confs/transmission.subdomain.conf.sample
root/defaults/proxy-confs/transmission.subfolder.conf.sample

This is essentially the same thing as the api blocks that were recently added to Sonarr/Radarr.
I've included the proposed change for api with optional baseurl in #170

Add rpc locations for transmission proxies

---

root/defaults/proxy-confs/jackett.subdomain.conf.sample
root/defaults/proxy-confs/jackett.subfolder.conf.sample
root/defaults/proxy-confs/nzbhydra.subdomain.conf.sample
root/defaults/proxy-confs/nzbhydra.subfolder.conf.sample
root/defaults/proxy-confs/radarr.subdomain.conf.sample
root/defaults/proxy-confs/sabnzbd.subdomain.conf.sample
root/defaults/proxy-confs/sonarr.subdomain.conf.sample
root/defaults/proxy-confs/tautulli.subdomain.conf.sample
root/defaults/proxy-confs/transmission.subdomain.conf.sample

The locations below use regex and my previous commit left the "not regex" location indicator. Also jackett uses `/api` and `/dl`. Lastly, Hydra uses an API location as well.

Fixes for api locations

---

root/defaults/proxy-confs/rutorrent.subdomain.conf.sample

This one does NOT include the optional subfolder/baseurl for the RPC2 location because rutorrent does not actually use a subfolder/baseurl and this was accomplished with an nginx rewrite for the subfolder conf. the RPC2 location is still included for the purpose of avoiding auth and allowing apps to communicate without nginx auth.

Add rutorrent subdomain proxy sample

---

root/defaults/proxy-confs/pihole.subdomain.conf.sample
root/defaults/proxy-confs/pihole.subfolder.conf.sample

This one was tricky at first. The `/admin` location is actually kind of the primary focus with pihole but the `/` location is still important. Both of the locations may or may not require auth which is why i've got what seems like duplicated configs here.

Add pihole proxy config samples

---

root/defaults/proxy-confs/bazarr.subfolder.conf.sample

Bazarr needs a trailing slash in its settings. The config works, I've just added the trailing slash to the comment.

Add trailing slash to bazarr comment

---

root/defaults/proxy-confs/ombi.subdomain.conf.sample
root/defaults/proxy-confs/ombi.subfolder.conf.sample

The rewrite that was removed is no longer needed (hasn't been for a while) and wasn't in the subdomain conf anyway.
The stuff added is for ombi's swagger api.

Add Ombi swagger api proxy configs

---

Dockerfile

+ use python3 for certbot, as failban uses it, so no double up on python
+ clear the root cache for pip stuff (-14 MB) 
+ clear out other cruft from pip in the cleanup stage
+ test/before                latest              9c0ecad6ffed        21 minutes ago      345MB
+ test/after                 latest              399297cfab1c        2 minutes ago       246MB
+ needs testing , hence only on the x86-64 Dockerfile
+ personally only tested that it builds locally and nothing else as yet

use python3 for certbot, clear root, clear pip cruft

---

README.md
readme-vars.yml
root/defaults/ssl.conf

Enabled TLS version 1.3
TLS 1.3 support was added in OpenSSL 1.1.1 which was included in Apline Linux 3.9

Enabled TLS 1.3

---

README.md
root/defaults/nginx.conf
root/defaults/proxy.conf

Fixes these errors
```
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
```
and
```
nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size
```

Hash errors

---

Dockerfile.aarch64

actually rebasing to 3.9 for aarch64

---

root/etc/cont-init.d/15-urllib

Quick and dirty fix, but easy to remove when there's a more elegant solution.
Closes https://github.com/linuxserver/docker-letsencrypt/issues/308

Fix urllib version

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/etc/cont-init.d/50-config

@aptalca if you decide to merge [this](https://github.com/linuxserver/reverse-proxy-confs/pull/46) then this PR stops the LICENSE file from cluttering up the proxy conf folder.  
I've left README.md in there as that might be useful.

Exclude LICENSE from proxy conf folders.

---

README.md
readme-vars.yml
root/defaults/default

enable http to https redirect by default

---

README.md
readme-vars.yml
root/etc/cont-init.d/50-config

This commit is a follow-up for #232, which changed DuckDNS to only support wildcards (`*.mysubdomain.duckdns.org`).
This commit tries to mimic the old behavior before #232 with additional support for wildcards. Ie. if `SUBDOMAINS` is set to `wildcard` as instructed, a wildcard cert is requested as currently. Otherwise certificate will be for the main domain as it used to be before #232.

Allow getting a cert for the main domain with DuckDNS

---

README.md
readme-vars.yml
root/defaults/default

Mark https redirect block as default server

---

root/defaults/proxy.conf
root/defaults/ssl.conf

Was reading through this https://blog.cloudflare.com/introducing-0-rtt/ a few months ago and had this branch waiting for the Alpine base image update which brought a compatible version of nginx http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_early_data
I've tested this and it works fine. I left it enabled by default since TLS 1.3 is enabled by default as well.

Add ssl_early_data directives

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/dns-conf/linode.ini
root/etc/cont-init.d/50-config

Adding support for [certbot-dns-linode](https://github.com/certbot/certbot/tree/master/certbot-dns-linode) plugin.
I tested this by building the Dockerfile on my home unraid server. It worked fine.

Adding certbot-dns-linode

---

readme-vars.yml
root/defaults/dns-conf/google.ini
root/defaults/dns-conf/google.json
root/etc/cont-init.d/50-config

GCP Google Cloud DNS cannot authenticate when using a `.ini` file with service account credentials.
As stated in [Certbot Google DNS Documentation](https://certbot-dns-google.readthedocs.io/en/stable/), it is looking for a `.json` file.
[Certbot Documentation](https://certbot.eff.org/docs/using.html#certbot-command-line-options) also states it is looking for a `.json` file, compared to other plugins that state it is looking for a `.ini` file.
When using the `.ini` file, the container produces the …

Google Cloud DNS needs a .json for authentication

---

root/defaults/ldap.conf

When using `auth_request` the variables from the parent proxy are conflicting and causing 404 errors.
Ref: https://github.com/linuxserver/reverse-proxy-confs/pull/138

Fix upstream auth vars

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/jail.local
root/etc/cont-init.d/50-config

- Add propagation parameter for dns validation
- Add whois from repo (to replace busybox version)
- Force renewal after changing duckdns token
- Blank out optional param values
- Change fail2ban default ban action to `iptables-allports`, which seems to be more widely supported
closes #442 
closes #427 
closes #428 
closes #151 
~~Awaiting user testing and feedback~~ user confirmed working with transip

Add propagation parameter for dns validation, add whois

---

root/defaults/fail2ban/filter.d/nginx-deny.conf
root/defaults/jail.local

fail2ban filter for nginx deny statements
add a custom filter to handle nginx deny statements
because we discuss allow and deny statements with users but don't offer a way for fail2ban to react to them. sadly, the default configs also don't handle deny statements (i should probably submit a PR)
from logs (these are actual attempt to intrude on my stuff, not created by me for testing.)
```
2020/05/08 12:22:24 [error] 403#403: *16830 access forbidden by rule, client: 209.17.96.250, server: …
```

fail2ban support for deny statements

---

Dockerfile
Dockerfile.aarch64
Dockerfile.armhf
README.md
readme-vars.yml
root/defaults/ssl.conf
root/etc/cont-init.d/50-config

More clarity on which settings are Mozilla Recommendations vs Linuxserver.io defaults
Add `ssl_trusted_certificate` (brought up in https://github.com/linuxserver/docker-letsencrypt/pull/461 and is also part of the Mozilla spec)
Include Mozilla Guideline version so we know when it needs to be updated
Side notes:
Moved HSTS to the bottom near the optional header lines. This puts anything we expect the user to enable all at the bottom.

Reformat ssl.conf

---

readme-vars.yml

`$EXTRA_DOMAINS` supports wildcards. Adding to the examples to make this explicit.
It wasn't immediately intuitive that I could use wildcards in `$EXTRA_DOMAINS` – so this ought to negate any questions about this.
Basically, just making sure the docs/README cover a case that feels like it might be more common than a corner-case.
Might also make sense to add comments about how one could look at the [`certbot` documentation][certbot-docs] for more info – which I'm willing to do, though I'd appreciate being pointed in the right direction. If [this is the right place][certbot-mention-tack-d], then I can knock that out this afternoon. (Although this is for Webroot, not necessarily `nginx`.)
[certbot-docs]: https://certbot.eff.org/docs/
[certbot-mention-tack-d]: …

Adding explicit wildcard to $EXTRA_DOMAINS in docs/README
